### ISSUE TITLE
Update CSS Variables

### ISSUE THREAD

**Issue by ExistentialAlex** [ExistentialAlex/hewitson_dev#1]
# Summary
Update CSS variable from the ones sent via email.

## CSS
- Variables:
```scss
:root {
--grey0: #f8f8f8;
--grey1: #dbe1e8;
--grey2: #b2becd;
--grey3: #6c7983;
--grey4: #454e56;
--grey5: #2a2e35;
--grey6: #12181b;
--clr-primary: #b9d8c2;
--clr-secondary: #9ac2c9;
}
.Light {
--bg: (--grey0);
--bg-nav: --grey0);
--bg-dropdown: var(--grey0);
--text: var(--grey6);
--text-hover: var(--clr-primary);
--border-clr: var(--clr-primary);
}
.dark {
--bg: var(--grey5);
--bg-nav: var(--grey5);
--bg-dropdown: var(--grey6);
--text: var(--grey0);
--text-hover: var(--clr-secondary);
--border-clr: var(--clr-secondary);
}

```
- Update child elements to use the new variables to allow for potential theming later.

**Comment by ExistentialAlex** [comment]
New color scheme:
```scss
  
:root {
  /////////////////////
  // Colour Settings //
  /////////////////////

  --grad0: #b6d2f6;
  --grad1: #91bbf2;
  --grad2: #5b98ec;
  --grad3: #2478e5;
  --grad4: #155bb7;
  --grad5: #0f4080;
  --grad6: #071e3d;
  --clr-primary: #21E6C1;
  --clr-secondary: #2F89FC;
  --clr-light: #edf4fd;
  --clr-dark: #020912;
  --border-radius: 1rem;
  --shadow: rgba(0, 0, 0, 0.3) 0px 2px 5px 0px;

  .light {
    --bg: var(--clr-light);
    --bg-nav: var(--clr-light);
    --bg-dropdown: var(--clr-light);
    // --link: var(--grad0);
    // --link-hover: saturate(darken(var(--clr-link), 15%), 10%);
    --text: var(--clr-dark);
    --text-hover: var(--clr-primary);
    --border-clr: var(--grad0);
  }
  .dark {
    --bg: var(--clr-dark);
    --bg-nav: var(--clr-dark);
    --bg-dropdown: var(--clr-dark);
    --text: var(--grad0);
    --text-hover: var(--clr-secondary);
    --border-clr: var(--clr-secondary);
  }
}
```
