### ISSUE TITLE
Update bottom nav to fit better with site

### ISSUE THREAD

**Issue by ExistentialAlex** [ExistentialAlex/hewitson_dev#29]
# Summary
Whilst the current bottom nav is cool it doesn't really fit with the current site and has issues with the animations on iPhones.
Fix this to make it fit better with the current top nav.
A quick sketch can be found here:
![IMG_20200717_132011.jpg](https://user-images.githubusercontent.com/31949243/87785578-4fbd1a80-c830-11ea-940c-8065f9f9f323.jpg)

## HTML
- Simplify the existing code to remove the unnecessary structure
Something like this:
```html
<div class="navbar__container">
    <div class="navbar">
        <a
            *ngFor="let link of links"
            class="navbar__item"
            [routerLink]="link.url"
            routerLinkActive="navbar__item--active"
            (click)="move(link.position)"
        >
            <span class="navbar__icon"><fa-icon [icon]="link.icon"></fa-icon></span>
        </a>
    </div>
</div>
```

## CSS
- Update CSS to better fit with the top nav of the site
- A simpler structure should make things easy to update.
Something like the following:
```scss
.navbar {
  width: 100%;
  height: 4rem;
  background-color: var(--clr-primary);
  position: absolute;

  &__icon {
    &::after {
        // Add some styles here to get the line under the icon
    }
  }

// Container might no longer be necessary
  &__container {
    width: 100%;
    height: var(--nav-height-bottom);
    background-color: var(--bg-nav);
    display: flex;
    justify-content: flex-end;
    flex-direction: column;
    overflow: hidden;
    position: relative;
    box-shadow: var(--shadow);
  }
}
```

## TS
No logic updates should be necessary
