### ISSUE TITLE
Project Card

### ISSUE THREAD

**Issue by ExistentialAlex** [ExistentialAlex/hewitson_dev#4]
# Summary

Add a card to be displayed in the project list, it should include the project title, description, img and tags.
Create generic card styles and add these to the global styles, they will then be useable across the project(s)
Have the image be the background and the title at the bottom, then on hover, make the description float up.
Limit description length to 200 characters, that way all cards should be same height.

## HTML

- Add an encapsulating div, this is our card
- Add img tag
- Add h3 tag for title
- Add p tag for description
- Add check for if img tag is null
- if using img as div background, add style for this.

## CSS
- Possibly create an encapsulating div around the content that you use to move it up and down.

```scss
.project {
     background: url(img url) //if this is done, will need to be done programmatically

    :hover {
        .project__description {
            display: block;
            translate up //look into how this is done.
        }
    }

    &__img { //or use an image tag, though this may be trickier
        width: 100%;
        height: 100%;
    }

    &__title {

    }

    &__description {
        width: 100%;
        display: none;
    }
}
```

## TS
- Add project input
